spring:
  datasource:
    url: jdbc:mariadb://${testDbIp:127.0.0.1}:3306/sbhello_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldjlocal
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none